version: '3.8'

services:
  # HAProxy - Load Balancer для ClickHouse
  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy
    hostname: haproxy
    network_mode: host
    volumes:
      - /opt/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8404/stats"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Prometheus - Мониторинг метрик
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    network_mode: host
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:9099'
    restart: unless-stopped

  # Grafana - Визуализация метрик
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_HTTP_PORT=3000
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - /data/grafana:/var/lib/grafana
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
