version: '3.8'

services:
  clickhouse-02:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse-02
    hostname: clickhouse-02
    network_mode: host
    environment:
      CLICKHOUSE_DB: default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      # Bind mount к реальному диску (2-4 TB NVMe)
      - /data/clickhouse:/var/lib/clickhouse
      # Конфигурационные файлы (скопировать из shared-configs)
      - /opt/clickhouse/config/config.xml:/etc/clickhouse-server/config.d/config.xml
      - /opt/clickhouse/config/users.xml:/etc/clickhouse-server/users.d/users.xml
      # Логи
      - /var/log/clickhouse:/var/log/clickhouse-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper-02:
    image: zookeeper:3.8
    container_name: zookeeper-02
    hostname: zookeeper-02
    network_mode: host
    environment:
      ZOO_MY_ID: 2
      # VM-1: 192.168.9.110, VM-2: 192.168.9.111, VM-3: 192.168.9.112
      ZOO_SERVERS: server.1=192.168.9.110:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=192.168.9.112:2888:3888;2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_MAX_CLIENT_CNXNS: 0
    volumes:
      # Bind mount к реальному диску
      - /data/zookeeper:/data
      - /var/log/zookeeper:/datalog
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
